version: '3.7'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: myphpapp-db
    environment: 
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: somedatabase
    volumes:
      - ./data:/var/lib/mysql

volumes:
  my-vol:
    name: myvol